import random

genres = [
    "Platform",
    "Shooter",
    "Fighting",
    "Beat 'em up",
    "Stealth",
    "Survival",
    "Rhythm",
    "Survival horror",
    "Metroidvania",
    "Text adventure",
    "Graphic adventure",
    "Interactive movie",
    "Real-time 3D adventure",
    "Action RPG",
    "MMORPG",
    "Roguelikes",
    "Tactical RPG",
    "Sandbox RPG",
    "First-person party-based RPG",
    "Cultural differences",
    "Fantasy",
    "Construction and management simulation",
    "Life simulation",
    "Vehicle simulation",
    "Artillery",
    "Real-time strategy (RTS)",
    "Real-time tactics (RTT)",
    "Multiplayer online battle arena (MOBA)",
    "Tower defense",
    "Turn-based strategy (TBS)",
    "Turn-based tactics (TBT)",
    "Wargame",
    "Grand strategy",
    "Racing",
    "Sports",
    "Competitive",
    "Sports-based fighting",
    "MMO",
    "Casual",
    "Party",
    "Programming",
    "Logic",
    "Trivia",
    "Board / Card",
    "Casual",
    "Educational",
    "Electronic sports",
    "Serious"
]

c1 = random.choice(genres)
genres.remove(c1)
print(" ".join([c1, random.choice(genres)]))
